### ISSUE TITLE
question

### ISSUE THREAD

**Issue by wemanzoz** [Andre-Unicode/cluster#1]
if it got outdated, what should i do to update it?

**Comment by Andre-Unicode** [comment]
Compile the cheat, attach a debugger to csgo, inject, and step thru the initialization process. If there where any major changes that made the cheat unusable, you will figure it out there. Any other outdated stuff that you cannot find during the initialization, will not behave correctly, and thus most likely result in a crash. Ctach the crash with your debuggger, and look at the callstack (where the crash came from), and you will easily be able to figure out what caused it.
